name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '22 10 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.14.0]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Fetch latest data
      run: |-
        pip install poetry==1.8.4
        cd app
        poetry install
        poetry run pwhlelo getseason 5
        poetry run pwhlelo cleandata
        poetry run pwhlelo calculate
        poetry run pwhlelo projections
        poetry run pwhlelo chartable
        cd ..
        ./move_data.sh
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: pwhl-elo-frontend/package-lock.json
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: publish site
      run: |-
        git config --global user.name 'eric'
        git config --global user.email 'ericjohannes@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        cd pwhl-elo-frontend
        npm ci
        npm run deploy
        cd ..
    - name: Commit and push
      run: |-
        git config --global user.name 'eric'
        git config --global user.email 'ericjohannes@users.noreply.github.com'
        git add -A
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push